### ISSUE TITLE
[FEATURE_REQUEST] Ability to use prefix for tables

### ISSUE THREAD

**Issue by Taimoor-Tariq** [QuiltServerTools/Ledger-Databases#15]
Maybe add an option in the config to add table prefixes so its easier to setup multiple plugins/mods using the same database.
I am trying to use the same DB for all my server plugins and its hard to navigate the tables. LuckPerms makes it easier by giving us an option to set a table prefix. So having that in Ledger would be really helpful

For example
```TOML
[database_extensions]
# ... other options
table_prefix = "ledger_"
```
